<?php

use Illuminate\Database\Seeder;

class UrlStatsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('url_stats')->delete();
        
        \DB::table('url_stats')->insert(array (
            0 => 
            array (
                'id' => null,
                'url_id' => 57,
                'platform' => 'Windows',
                'browser' => 'Chrome',
                'ip' => '195.189.88.118',
                'country_name' => 'Colombia',
                'country_code' => 'CO',
                'http_referer' => NULL,
                'created_at' => '2016-10-19 15:21:48',
                'updated_at' => '2016-10-19 15:21:48',
            ),
            1 => 
            array (
                'id' => null,
                'url_id' => 57,
                'platform' => 'Windows',
                'browser' => 'Chrome',
                'ip' => '195.189.88.118',
                'country_name' => 'Colombia',
                'country_code' => 'CO',
                'http_referer' => NULL,
                'created_at' => '2016-10-19 22:11:48',
                'updated_at' => '2016-10-19 22:11:48',
            ),
            2 => 
            array (
                'id' => null,
                'url_id' => 57,
                'platform' => 'Windows',
                'browser' => 'Chrome',
                'ip' => '195.189.88.118',
                'country_name' => 'Colombia',
                'country_code' => 'CO',
                'http_referer' => NULL,
                'created_at' => '2016-10-19 22:11:59',
                'updated_at' => '2016-10-19 22:11:59',
            ),
            3 => 
            array (
                'id' => null,
                'url_id' => 57,
                'platform' => 'Macintosh',
                'browser' => 'Chrome',
                'ip' => '195.189.88.118',
                'country_name' => 'Colombia',
                'country_code' => 'CO',
                'http_referer' => NULL,
                'created_at' => '2016-10-19 22:12:50',
                'updated_at' => '2016-10-19 22:12:50',
            ),
            4 => 
            array (
                'id' => null,
                'url_id' => 57,
                'platform' => 'Macintosh',
                'browser' => 'Chrome',
                'ip' => '195.189.88.118',
                'country_name' => 'Canada',
                'country_code' => 'CA',
                'http_referer' => NULL,
                'created_at' => '2016-10-19 22:12:53',
                'updated_at' => '2016-10-19 22:12:53',
            ),
            5 => 
            array (
                'id' => null,
                'url_id' => 57,
                'platform' => 'Macintosh',
                'browser' => 'Chrome',
                'ip' => '195.189.88.118',
                'country_name' => 'Canada',
                'country_code' => 'CA',
                'http_referer' => NULL,
                'created_at' => '2016-10-19 22:13:09',
                'updated_at' => '2016-10-19 22:13:09',
            ),
            6 => 
            array (
                'id' => null,
                'url_id' => 57,
                'platform' => 'Macintosh',
                'browser' => 'Chrome',
                'ip' => '195.189.88.118',
                'country_name' => 'Canada',
                'country_code' => 'CA',
                'http_referer' => NULL,
                'created_at' => '2016-10-19 22:13:36',
                'updated_at' => '2016-10-19 22:13:36',
            ),
            7 => 
            array (
                'id' => null,
                'url_id' => 57,
                'platform' => 'Linux',
                'browser' => 'Chrome',
                'ip' => '195.189.88.118',
                'country_name' => 'Canada',
                'country_code' => 'CA',
                'http_referer' => NULL,
                'created_at' => '2016-10-19 22:14:08',
                'updated_at' => '2016-10-19 22:14:08',
            ),
            8 => 
            array (
                'id' => null,
                'url_id' => 57,
                'platform' => 'Linux',
                'browser' => 'Chrome',
                'ip' => '195.189.88.118',
                'country_name' => 'Switzerland',
                'country_code' => 'CH',
                'http_referer' => NULL,
                'created_at' => '2016-10-19 22:14:23',
                'updated_at' => '2016-10-19 22:14:23',
            ),
            9 => 
            array (
                'id' => null,
                'url_id' => 57,
                'platform' => 'Linux',
                'browser' => 'Chrome',
                'ip' => '195.189.88.118',
                'country_name' => 'Switzerland',
                'country_code' => 'CH',
                'http_referer' => NULL,
                'created_at' => '2016-10-19 22:14:32',
                'updated_at' => '2016-10-19 22:14:32',
            ),
            10 => 
            array (
                'id' => null,
                'url_id' => 57,
                'platform' => 'Windows',
                'browser' => 'Chrome',
                'ip' => '195.189.88.118',
                'country_name' => 'Switzerland',
                'country_code' => 'CH',
                'http_referer' => NULL,
                'created_at' => '2016-10-19 22:15:47',
                'updated_at' => '2016-10-19 22:15:47',
            ),
            11 => 
            array (
                'id' => null,
                'url_id' => 57,
                'platform' => 'Windows',
                'browser' => 'Chrome',
                'ip' => '195.189.88.118',
                'country_name' => 'Switzerland',
                'country_code' => 'CH',
                'http_referer' => NULL,
                'created_at' => '2016-10-19 22:34:53',
                'updated_at' => '2016-10-19 22:34:53',
            ),
            12 => 
            array (
                'id' => null,
                'url_id' => 57,
                'platform' => 'Windows',
                'browser' => 'Chrome',
                'ip' => '195.189.88.118',
                'country_name' => 'Switzerland',
                'country_code' => 'CH',
                'http_referer' => NULL,
                'created_at' => '2016-10-19 22:35:31',
                'updated_at' => '2016-10-19 22:35:31',
            ),
            13 => 
            array (
                'id' => null,
                'url_id' => 57,
                'platform' => 'Windows',
                'browser' => 'Chrome',
                'ip' => '195.189.88.118',
                'country_name' => 'Switzerland',
                'country_code' => 'CH',
                'http_referer' => NULL,
                'created_at' => '2016-10-19 22:36:58',
                'updated_at' => '2016-10-19 22:36:58',
            ),
            14 => 
            array (
                'id' => null,
                'url_id' => 57,
                'platform' => 'Windows',
                'browser' => 'Chrome',
                'ip' => '195.189.88.118',
                'country_name' => 'Switzerland',
                'country_code' => 'CH',
                'http_referer' => NULL,
                'created_at' => '2016-10-19 22:37:18',
                'updated_at' => '2016-10-19 22:37:18',
            ),
            15 => 
            array (
                'id' => null,
                'url_id' => 57,
                'platform' => 'Windows',
                'browser' => 'Chrome',
                'ip' => '195.189.88.118',
                'country_name' => 'Switzerland',
                'country_code' => 'CH',
                'http_referer' => NULL,
                'created_at' => '2016-10-19 22:37:31',
                'updated_at' => '2016-10-19 22:37:31',
            ),
            16 => 
            array (
                'id' => null,
                'url_id' => 57,
                'platform' => 'Windows',
                'browser' => 'Chrome',
                'ip' => '195.189.88.118',
                'country_name' => 'Switzerland',
                'country_code' => 'CH',
                'http_referer' => NULL,
                'created_at' => '2016-10-20 21:39:02',
                'updated_at' => '2016-10-20 21:39:02',
            ),
            17 => 
            array (
                'id' => null,
                'url_id' => 57,
                'platform' => 'Windows',
                'browser' => 'Chrome',
                'ip' => '195.189.88.118',
                'country_name' => 'United States',
                'country_code' => 'US',
                'http_referer' => NULL,
                'created_at' => '2016-10-20 23:26:15',
                'updated_at' => '2016-10-20 23:26:15',
            ),
            18 => 
            array (
                'id' => null,
                'url_id' => 9,
                'platform' => 'Windows',
                'browser' => 'Chrome',
                'ip' => '195.189.88.118',
                'country_name' => 'United States',
                'country_code' => 'US',
                'http_referer' => NULL,
                'created_at' => '2016-10-22 23:19:33',
                'updated_at' => '2016-10-22 23:19:33',
            ),
            19 => 
            array (
                'id' => null,
                'url_id' => 57,
                'platform' => 'Windows',
                'browser' => 'MSIE',
                'ip' => '195.189.88.118',
                'country_name' => 'United States',
                'country_code' => 'US',
                'http_referer' => NULL,
                'created_at' => '2016-10-22 23:21:30',
                'updated_at' => '2016-10-22 23:21:30',
            ),
            20 => 
            array (
                'id' => null,
                'url_id' => 57,
                'platform' => 'Windows',
                'browser' => 'MSIE',
                'ip' => '195.189.88.118',
                'country_name' => 'United States',
                'country_code' => 'US',
                'http_referer' => NULL,
                'created_at' => '2016-10-22 23:21:54',
                'updated_at' => '2016-10-22 23:21:54',
            ),
            21 => 
            array (
                'id' => null,
                'url_id' => 9,
                'platform' => 'Windows',
                'browser' => 'Chrome',
                'ip' => '195.189.88.118',
                'country_name' => 'United States',
                'country_code' => 'US',
                'http_referer' => NULL,
                'created_at' => '2016-10-23 00:28:11',
                'updated_at' => '2016-10-23 00:28:11',
            ),
            22 => 
            array (
                'id' => null,
                'url_id' => 57,
                'platform' => 'Windows',
                'browser' => 'Chrome',
                'ip' => '195.189.88.118',
                'country_name' => 'United States',
                'country_code' => 'US',
                'http_referer' => NULL,
                'created_at' => '2016-10-23 22:56:02',
                'updated_at' => '2016-10-23 22:56:02',
            ),
            23 => 
            array (
                'id' => null,
                'url_id' => 57,
                'platform' => 'Windows',
                'browser' => 'Chrome',
                'ip' => '195.189.88.118',
                'country_name' => 'United States',
                'country_code' => 'US',
                'http_referer' => NULL,
                'created_at' => '2016-10-23 22:56:53',
                'updated_at' => '2016-10-23 22:56:53',
            ),
            24 => 
            array (
                'id' => null,
                'url_id' => 57,
                'platform' => 'Windows',
                'browser' => 'Chrome',
                'ip' => '195.189.88.118',
                'country_name' => 'United States',
                'country_code' => 'US',
                'http_referer' => NULL,
                'created_at' => '2016-10-23 22:57:37',
                'updated_at' => '2016-10-23 22:57:37',
            ),
            25 => 
            array (
                'id' => null,
                'url_id' => 57,
                'platform' => 'Windows',
                'browser' => 'Chrome',
                'ip' => '195.189.88.118',
                'country_name' => 'United States',
                'country_code' => 'US',
                'http_referer' => NULL,
                'created_at' => '2016-10-23 22:57:45',
                'updated_at' => '2016-10-23 22:57:45',
            ),
            26 => 
            array (
                'id' => null,
                'url_id' => 57,
                'platform' => 'Windows',
                'browser' => 'Chrome',
                'ip' => '195.189.88.118',
                'country_name' => 'United States',
                'country_code' => 'US',
                'http_referer' => NULL,
                'created_at' => '2016-10-23 22:58:29',
                'updated_at' => '2016-10-23 22:58:29',
            ),
            27 => 
            array (
                'id' => null,
                'url_id' => 57,
                'platform' => 'Windows',
                'browser' => 'Chrome',
                'ip' => '195.189.88.118',
                'country_name' => 'United States',
                'country_code' => 'US',
                'http_referer' => NULL,
                'created_at' => '2016-10-23 22:59:25',
                'updated_at' => '2016-10-23 22:59:25',
            ),
            28 => 
            array (
                'id' => null,
                'url_id' => 57,
                'platform' => 'Windows',
                'browser' => 'Chrome',
                'ip' => '195.189.88.118',
                'country_name' => 'United States',
                'country_code' => 'US',
                'http_referer' => NULL,
                'created_at' => '2016-10-23 22:59:45',
                'updated_at' => '2016-10-23 22:59:45',
            ),
            29 => 
            array (
                'id' => null,
                'url_id' => 57,
                'platform' => 'Windows',
                'browser' => 'Chrome',
                'ip' => '195.189.88.118',
                'country_name' => 'United States',
                'country_code' => 'US',
                'http_referer' => NULL,
                'created_at' => '2016-10-23 22:59:48',
                'updated_at' => '2016-10-23 22:59:48',
            ),
            30 => 
            array (
                'id' => null,
                'url_id' => 57,
                'platform' => 'Windows',
                'browser' => 'Chrome',
                'ip' => '195.189.88.118',
                'country_name' => 'United States',
                'country_code' => 'US',
                'http_referer' => NULL,
                'created_at' => '2016-10-23 23:01:01',
                'updated_at' => '2016-10-23 23:01:01',
            ),
            31 => 
            array (
                'id' => null,
                'url_id' => 57,
                'platform' => 'Windows',
                'browser' => 'Chrome',
                'ip' => '195.189.88.118',
                'country_name' => 'United States',
                'country_code' => 'US',
                'http_referer' => NULL,
                'created_at' => '2016-10-23 23:01:04',
                'updated_at' => '2016-10-23 23:01:04',
            ),
            32 => 
            array (
                'id' => null,
                'url_id' => 57,
                'platform' => 'Windows',
                'browser' => 'Chrome',
                'ip' => '195.189.88.118',
                'country_name' => 'United States',
                'country_code' => 'US',
                'http_referer' => NULL,
                'created_at' => '2016-10-23 23:01:13',
                'updated_at' => '2016-10-23 23:01:13',
            ),
            33 => 
            array (
                'id' => null,
                'url_id' => 57,
                'platform' => 'Windows',
                'browser' => 'Chrome',
                'ip' => '195.189.88.118',
                'country_name' => 'United States',
                'country_code' => 'US',
                'http_referer' => NULL,
                'created_at' => '2016-10-23 23:01:32',
                'updated_at' => '2016-10-23 23:01:32',
            ),
            34 => 
            array (
                'id' => null,
                'url_id' => 57,
                'platform' => 'Windows',
                'browser' => 'Chrome',
                'ip' => '195.189.88.118',
                'country_name' => 'Poland',
                'country_code' => 'PL',
                'http_referer' => NULL,
                'created_at' => '2016-10-23 23:01:35',
                'updated_at' => '2016-10-23 23:01:35',
            ),
            35 => 
            array (
                'id' => null,
                'url_id' => 57,
                'platform' => 'Windows',
                'browser' => 'Chrome',
                'ip' => '195.189.88.118',
                'country_name' => 'Poland',
                'country_code' => 'PL',
                'http_referer' => NULL,
                'created_at' => '2016-10-23 23:03:39',
                'updated_at' => '2016-10-23 23:03:39',
            ),
            36 => 
            array (
                'id' => null,
                'url_id' => 57,
                'platform' => 'Windows',
                'browser' => 'Chrome',
                'ip' => '195.189.88.118',
                'country_name' => 'Poland',
                'country_code' => 'PL',
                'http_referer' => NULL,
                'created_at' => '2016-10-23 23:04:17',
                'updated_at' => '2016-10-23 23:04:17',
            ),
            37 => 
            array (
                'id' => null,
                'url_id' => 57,
                'platform' => 'Windows',
                'browser' => 'Chrome',
                'ip' => '195.189.88.118',
                'country_name' => 'Poland',
                'country_code' => 'PL',
                'http_referer' => NULL,
                'created_at' => '2016-10-23 23:04:38',
                'updated_at' => '2016-10-23 23:04:38',
            ),
            38 => 
            array (
                'id' => null,
                'url_id' => 57,
                'platform' => 'Windows',
                'browser' => 'Chrome',
                'ip' => '195.189.88.118',
                'country_name' => 'Poland',
                'country_code' => 'PL',
                'http_referer' => 'http://google.com/',
                'created_at' => '2016-10-23 23:20:35',
                'updated_at' => '2016-10-23 23:20:35',
            ),
            39 => 
            array (
                'id' => null,
                'url_id' => 57,
                'platform' => 'Windows',
                'browser' => 'Chrome',
                'ip' => '195.189.88.118',
                'country_name' => 'Poland',
                'country_code' => 'PL',
                'http_referer' => 'http://localhost:8000/ou7NmI/stats',
                'created_at' => '2016-10-23 23:20:54',
                'updated_at' => '2016-10-23 23:20:54',
            ),
            40 => 
            array (
                'id' => null,
                'url_id' => 57,
                'platform' => 'Linux',
                'browser' => 'Chrome',
                'ip' => '195.189.88.118',
                'country_name' => 'Poland',
                'country_code' => 'PL',
                'http_referer' => NULL,
                'created_at' => '2016-10-26 12:11:52',
                'updated_at' => '2016-10-26 12:11:52',
            ),
            41 => 
            array (
                'id' => null,
                'url_id' => 57,
                'platform' => 'Linux',
                'browser' => 'MSIE',
                'ip' => '195.189.88.118',
                'country_name' => 'Poland',
                'country_code' => 'PL',
                'http_referer' => NULL,
                'created_at' => '2016-10-26 12:33:28',
                'updated_at' => '2016-10-26 12:33:28',
            ),
            42 => 
            array (
                'id' => null,
                'url_id' => 57,
                'platform' => 'Linux',
                'browser' => 'Chrome',
                'ip' => '195.189.88.118',
                'country_name' => 'Poland',
                'country_code' => 'PL',
                'http_referer' => NULL,
                'created_at' => '2016-10-26 22:59:16',
                'updated_at' => '2016-10-26 22:59:16',
            ),
            43 => 
            array (
                'id' => null,
                'url_id' => 57,
                'platform' => 'Linux',
                'browser' => 'Chrome',
                'ip' => '195.189.88.118',
                'country_name' => 'Poland',
                'country_code' => 'PL',
                'http_referer' => 'http://localhost:8000/TMqgL3/stats',
                'created_at' => '2016-10-26 23:22:26',
                'updated_at' => '2016-10-26 23:22:26',
            ),
            44 => 
            array (
                'id' => null,
                'url_id' => 57,
                'platform' => 'Linux',
                'browser' => 'Chrome',
                'ip' => '195.189.88.118',
                'country_name' => 'Poland',
                'country_code' => 'PL',
                'http_referer' => 'http://localhost:8000/TMqgL3/stats',
                'created_at' => '2016-10-26 23:23:15',
                'updated_at' => '2016-10-26 23:23:15',
            ),
            45 => 
            array (
                'id' => null,
                'url_id' => 57,
                'platform' => 'Linux',
                'browser' => 'Chrome',
                'ip' => '195.189.88.118',
                'country_name' => 'Poland',
                'country_code' => 'PL',
                'http_referer' => 'http://localhost:8000/',
                'created_at' => '2016-09-25 14:54:15',
                'updated_at' => '2016-10-27 14:54:15',
            ),
            46 => 
            array (
                'id' => null,
                'url_id' => 57,
                'platform' => 'Linux',
                'browser' => 'Chrome',
                'ip' => '195.189.88.118',
                'country_name' => 'Poland',
                'country_code' => 'PL',
                'http_referer' => 'http://localhost:8000/',
                'created_at' => '2016-10-27 14:54:17',
                'updated_at' => '2016-10-27 14:54:17',
            ),
            47 => 
            array (
                'id' => null,
                'url_id' => 57,
                'platform' => 'Linux',
                'browser' => 'Chrome',
                'ip' => '195.189.88.118',
                'country_name' => 'Poland',
                'country_code' => 'PL',
                'http_referer' => 'http://localhost:8000/',
                'created_at' => '2016-10-25 23:54:17',
                'updated_at' => '2016-10-27 14:54:17',
            ),
            48 => 
            array (
                'id' => null,
                'url_id' => 57,
                'platform' => 'Macintosh',
                'browser' => 'Chrome',
                'ip' => '195.189.88.118',
                'country_name' => 'Poland',
                'country_code' => 'PL',
                'http_referer' => 'http://localhost:8000/',
                'created_at' => '2016-10-25 18:54:22',
                'updated_at' => '2016-10-27 14:54:22',
            ),
            49 => 
            array (
                'id' => null,
                'url_id' => 57,
                'platform' => 'Macintosh',
                'browser' => 'Chrome',
                'ip' => '195.189.88.118',
                'country_name' => 'Poland',
                'country_code' => 'PL',
                'http_referer' => 'http://localhost:8000/',
                'created_at' => '2016-10-26 14:54:24',
                'updated_at' => '2016-10-27 14:54:24',
            ),
            50 => 
            array (
                'id' => null,
                'url_id' => 57,
                'platform' => 'Macintosh',
                'browser' => 'Chrome',
                'ip' => '195.189.88.118',
                'country_name' => 'Poland',
                'country_code' => 'PL',
                'http_referer' => 'http://localhost:8000/',
                'created_at' => '2016-10-27 14:54:27',
                'updated_at' => '2016-10-27 14:54:27',
            ),
            51 => 
            array (
                'id' => null,
                'url_id' => 57,
                'platform' => 'Macintosh',
                'browser' => 'Chrome',
                'ip' => '195.189.88.118',
                'country_name' => 'Poland',
                'country_code' => 'PL',
                'http_referer' => 'http://localhost:8000/',
                'created_at' => '2016-10-27 14:54:28',
                'updated_at' => '2016-10-27 14:54:28',
            ),
            52 => 
            array (
                'id' => null,
                'url_id' => 57,
                'platform' => 'Macintosh',
                'browser' => 'Chrome',
                'ip' => '195.189.88.118',
                'country_name' => 'Poland',
                'country_code' => 'PL',
                'http_referer' => 'http://localhost:8000/',
                'created_at' => '2016-10-27 14:54:29',
                'updated_at' => '2016-10-27 14:54:29',
            ),
            53 => 
            array (
                'id' => null,
                'url_id' => 57,
                'platform' => 'Windows',
                'browser' => 'Opera',
                'ip' => '195.189.88.118',
                'country_name' => 'Poland',
                'country_code' => 'PL',
                'http_referer' => 'http://localhost:8000/',
                'created_at' => '2016-10-27 14:54:37',
                'updated_at' => '2016-10-27 14:54:37',
            ),
            54 => 
            array (
                'id' => null,
                'url_id' => 57,
                'platform' => 'Windows',
                'browser' => 'Opera',
                'ip' => '195.189.88.118',
                'country_name' => 'Poland',
                'country_code' => 'PL',
                'http_referer' => 'http://localhost:8000/',
                'created_at' => '2016-10-27 14:54:37',
                'updated_at' => '2016-10-27 14:54:37',
            ),
            55 => 
            array (
                'id' => null,
                'url_id' => 57,
                'platform' => 'Windows',
                'browser' => 'Opera',
                'ip' => '195.189.88.118',
                'country_name' => 'Poland',
                'country_code' => 'PL',
                'http_referer' => 'http://localhost:8000/ZGNQ6v/stats?range=24h',
                'created_at' => '2016-10-20 18:03:23',
                'updated_at' => '2016-10-27 18:03:23',
            ),
            56 => 
            array (
                'id' => null,
                'url_id' => 57,
                'platform' => 'Windows',
                'browser' => 'Opera',
                'ip' => '195.189.88.118',
                'country_name' => 'Poland',
                'country_code' => 'PL',
                'http_referer' => 'http://localhost:8000/ZGNQ6v/stats?range=24h',
                'created_at' => '2016-09-15 18:03:25',
                'updated_at' => '2016-10-27 18:03:25',
            ),
            57 => 
            array (
                'id' => null,
                'url_id' => 57,
                'platform' => 'Windows',
                'browser' => 'Opera',
                'ip' => '195.189.88.118',
                'country_name' => 'Poland',
                'country_code' => 'PL',
                'http_referer' => 'http://localhost:8000/ZGNQ6v/stats?range=24h',
                'created_at' => '2016-09-30 18:03:28',
                'updated_at' => '2016-10-27 18:03:28',
            ),
            58 => 
            array (
                'id' => null,
                'url_id' => 57,
                'platform' => 'Windows',
                'browser' => 'Opera',
                'ip' => '195.189.88.118',
                'country_name' => 'Poland',
                'country_code' => 'PL',
                'http_referer' => 'http://localhost:8000/ZGNQ6v/stats?range=24h',
                'created_at' => '2016-09-27 18:03:32',
                'updated_at' => '2016-10-27 18:03:32',
            ),
            59 => 
            array (
                'id' => null,
                'url_id' => 57,
                'platform' => 'Windows',
                'browser' => 'Opera',
                'ip' => '195.189.88.118',
                'country_name' => 'Poland',
                'country_code' => 'PL',
                'http_referer' => 'http://localhost:8000/ZGNQ6v/stats?range=24h',
                'created_at' => '2016-10-22 18:03:36',
                'updated_at' => '2016-10-27 18:03:36',
            ),
            60 => 
            array (
                'id' => null,
                'url_id' => 57,
                'platform' => 'Windows',
                'browser' => 'MSIE',
                'ip' => '195.189.88.118',
                'country_name' => 'Poland',
                'country_code' => 'PL',
                'http_referer' => NULL,
                'created_at' => '2016-10-23 18:04:14',
                'updated_at' => '2016-10-27 18:04:14',
            ),
            61 => 
            array (
                'id' => null,
                'url_id' => 57,
                'platform' => 'Windows',
                'browser' => 'MSIE',
                'ip' => '195.189.88.118',
                'country_name' => 'Poland',
                'country_code' => 'PL',
                'http_referer' => NULL,
                'created_at' => '2016-10-24 18:04:17',
                'updated_at' => '2016-10-27 18:04:17',
            ),
            62 => 
            array (
                'id' => null,
                'url_id' => 57,
                'platform' => 'Windows',
                'browser' => 'MSIE',
                'ip' => '195.189.88.118',
                'country_name' => 'Poland',
                'country_code' => 'PL',
                'http_referer' => NULL,
                'created_at' => '2016-10-25 18:04:19',
                'updated_at' => '2016-10-27 18:04:19',
            ),
            63 => 
            array (
                'id' => null,
                'url_id' => 57,
                'platform' => 'Windows',
                'browser' => 'Opera',
                'ip' => '195.189.88.118',
                'country_name' => 'Poland',
                'country_code' => 'PL',
                'http_referer' => 'http://localhost:8000/vx8wG4/stats',
                'created_at' => '2016-10-31 14:02:05',
                'updated_at' => '2016-10-31 14:02:05',
            ),
            64 => 
            array (
                'id' => null,
                'url_id' => 57,
                'platform' => 'Windows',
                'browser' => 'Lynx',
                'ip' => '195.189.88.118',
                'country_name' => 'Poland',
                'country_code' => 'PL',
                'http_referer' => 'http://localhost:8000/vx8wG4/stats',
                'created_at' => '2016-10-31 14:02:06',
                'updated_at' => '2016-10-31 14:02:06',
            ),
            65 => 
            array (
                'id' => null,
                'url_id' => 57,
                'platform' => 'Windows',
                'browser' => 'Lynx',
                'ip' => '195.189.88.118',
                'country_name' => 'Poland',
                'country_code' => 'PL',
                'http_referer' => 'http://localhost:8000/vx8wG4/stats',
                'created_at' => '2016-10-31 14:02:08',
                'updated_at' => '2016-10-31 14:02:08',
            ),
            66 => 
            array (
                'id' => null,
                'url_id' => 57,
                'platform' => 'Windows',
                'browser' => 'Lynx',
                'ip' => '195.189.88.118',
                'country_name' => 'Poland',
                'country_code' => 'PL',
                'http_referer' => 'http://localhost:8000/uF7mOB/stats',
                'created_at' => '2016-11-02 23:46:36',
                'updated_at' => '2016-11-02 23:46:36',
            ),
            67 => 
            array (
                'id' => null,
                'url_id' => 57,
                'platform' => 'Windows',
                'browser' => 'Lynx',
                'ip' => '195.189.88.118',
                'country_name' => 'Poland',
                'country_code' => 'PL',
                'http_referer' => 'http://localhost:8000/ht0Pk1/stats',
                'created_at' => '2016-11-03 16:29:22',
                'updated_at' => '2016-11-03 16:29:22',
            ),
            68 => 
            array (
                'id' => null,
                'url_id' => 57,
                'platform' => 'Windows',
                'browser' => 'Lynx',
                'ip' => '195.189.88.118',
                'country_name' => 'Poland',
                'country_code' => 'PL',
                'http_referer' => 'http://localhost:8000/ht0Pk1/stats',
                'created_at' => '2016-11-03 16:29:26',
                'updated_at' => '2016-11-03 16:29:26',
            ),
            69 => 
            array (
                'id' => null,
                'url_id' => 57,
                'platform' => 'Windows',
                'browser' => 'Lynx',
                'ip' => '195.189.88.118',
                'country_name' => 'Poland',
                'country_code' => 'PL',
                'http_referer' => 'http://localhost:8000/ht0Pk1/stats',
                'created_at' => '2016-11-03 16:29:30',
                'updated_at' => '2016-11-03 16:29:30',
            ),
        ));
        
        
    }
}
